Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  config.vm.define "inetRouter1" do |inetRouter1|
    inetRouter1.vm.box = "centos/7"
    inetRouter1.vm.hostname = "inetRouter1"
    inetRouter1.vm.network :private_network, ip: '192.168.250.1', adapter:  2, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter1-3"
    inetRouter1.vm.network :private_network, ip: '192.168.251.1', adapter:  3, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter1-2"
    inetRouter1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/ospf.yml"
      ansible.extra_vars = {
        "zebra_password" => "zebrapass",
        "enable_zebra_password" => "enablezebra",
        "zebra_eth1_ip" => "192.168.250.1/29",
        "zebra_eth2_ip" => "192.168.251.1/29",
        "ospf_password" => "ospfpass",
        "cost_eth1" => "200",
        "cost_eth2" => "20",
        "ospf_router_id" => "192.168.250.1",
        "ospf_network_1" => "192.168.250.0/29",
        "ospf_network_2" => "192.168.251.0/29",
        "desc_eth1" => "inetRouter1-3",
        "desc_eth2" => "inetRouter1-2"
      }
      ansible.verbose = true
    end
  end

  config.vm.define "inetRouter2" do |inetRouter2|
    inetRouter2.vm.box = "centos/7"
    inetRouter2.vm.hostname = "inetRouter2"
    inetRouter2.vm.network :private_network, ip: '192.168.251.2', adapter:  2, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter1-2"
    inetRouter2.vm.network :private_network, ip: '192.168.252.2', adapter:  3, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter3-2"
    inetRouter2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/ospf.yml"
      ansible.extra_vars = {
        "zebra_password" => "zebrapass",
        "enable_zebra_password" => "enablezebra",
        "zebra_eth1_ip" => "192.168.251.2/29",
        "zebra_eth2_ip" => "192.168.252.2/29",
        "ospf_password" => "ospfpass",
        "cost_eth1" => "20",
        "cost_eth2" => "20",
        "ospf_router_id" => "192.168.251.2",
        "ospf_network_1" => "192.168.251.0/29",
        "ospf_network_2" => "192.168.252.0/29",
        "desc_eth1" => "inetRouter1-2",
        "desc_eth2" => "inetRouter3-2"
      }
      ansible.verbose = true
    end
  end

  config.vm.define "inetRouter3" do |inetRouter3|
    inetRouter3.vm.box = "centos/7"
    inetRouter3.vm.hostname = "inetRouter3"
    inetRouter3.vm.network :private_network, ip: "192.168.252.1", adapter:  2, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter3-2"
    inetRouter3.vm.network :private_network, ip: "192.168.250.2", adapter:  3, netmask: "255.255.255.248", virtualbox__intnet: "inetRouter1-3"
    inetRouter3.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/ospf.yml"
      ansible.extra_vars = {
        "zebra_password" => "zebrapass",
        "enable_zebra_password" => "enablezebra",
        "zebra_eth1_ip" => "192.168.252.1/29",
        "zebra_eth2_ip" => "192.168.250.2/29",
        "ospf_password" => "ospfpass",
        "cost_eth1" => "20",
        "cost_eth2" => "200",
        "ospf_router_id" => "192.168.252.1",
        "ospf_network_1" => "192.168.252.0/29",
        "ospf_network_2" => "192.168.250.0/29",
        "desc_eth1" => "inetRouter3-2",
        "desc_eth2" => "inetRouter1-3"
      }
      ansible.verbose = true
    end
  end

  config.vm.provision "shell" do |shell|
    shell.path = "./files/sshd_cfg.sh"
  end 

end