# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  dDisk1 ="./Lab3-disk1.vdi"
  dDisk2 ="./Lab3-disk2.vdi"
  dDisk3 ="./Lab3-disk3.vdi"
  dDisk4 ="./Lab3-disk4.vdi"
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
 
  config.vm.provider "virtualbox" do |vb|
    if not File.exists?(dDisk1)
      vb.customize ['createhd', '--filename', dDisk1, '--variant', 'Fixed', '--size', 8 * 1024]
    end
    if not File.exists?(dDisk2)
      vb.customize ['createhd', '--filename', dDisk2, '--variant', 'Fixed', '--size', 8 * 1024]
    end
    if not File.exists?(dDisk3)
      vb.customize ['createhd', '--filename', dDisk3, '--variant', 'Fixed', '--size', 2 * 1024]
    end
    if not File.exists?(dDisk4)
        vb.customize ['createhd', '--filename', dDisk4, '--variant', 'Fixed', '--size', 2 * 1024]
    end
    
    vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata', '--portcount', 5]

    # Attaching the disks using the SATA controller
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', dDisk1]
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', dDisk2]
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', dDisk3]
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', dDisk4]
  
    
    
    #v.hostname = "lab3-host"
    #v.customize [ "createmedium", "disk", "--filename", "lab3-disk1.vdi",   "--format", "vdi", "--size", 1024 * 8 ]
    #v.customize [ "storageattach", :id , "--storagectl", "ICH6", "--port", "1", "--device", "0", "--type", "sata", "--medium", "lab3-disk1.vdi"]
  end
  config.vm.box = "centos/7"
  config.vm.box_version = "1803.01"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:v
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
