# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network :public_network, bridge: 'enp2s0'
    #web.vm.network :private_network, ip: '10.10.10.10'
  end

  config.vm.provision "shell" do |shell|
    shell.path = "./files/sshd_cfg.sh"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/web.yml"
    ansible.extra_vars = { "def_nginx_port" => "80","nginx_user" => "nginx",
     "nginx_access_log_path" =>"/var/log/nginx/access.log",
     "nginx_error_log_path" =>"/var/log/nginx/error.log",
    }
    ansible.verbose = true
  end

end
