Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "app" => ["appserver"],
      "app:vars" => { "listen_port" => "10.10.10.10"}
      }
      #ansible.extra_vars = {
      #  "deploy_user" => "vagrant",
      #  "nginx_sites" => {
      #    "rpproxy"=> [
      #      "listen 8080",
      #      "server_name 'reddit'",
      #      "location / { proxy_pass http://127.0.0.1:9292; }"
       #   ]
       #   }
      #}    
    end
  end
end
