Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "nginx_server" do |nginx|
    nginx.vm.box = "centos/7" # need to be commented when Debian like distro used
    #nginx.vm.box = "ubuntu/xenial64" # need to be uncoment when Debian like distro used
    nginx.vm.hostname = "appserver"
    nginx.vm.network :private_network, ip: "10.10.10.20"

    nginx.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "nginx" => ["nginx_server"],
      "nginx:vars" => { "def_nginx_port" => "8080",
        "nginx_user" => "nginx" # need to be commented when Debian like distro used
       # "nginx_user" => "www-data" # need to be uncoment when Debian like distro used
       }
      }    
    end
  end
end
