Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.box = "centos/7"
    inetRouter.vm.hostname = "inetRouter"
    inetRouter.vm.network :private_network, ip: '192.168.255.1', adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "irnet"
    inetRouter.vm.provision "shell", path: "./files/sshd_cfg.sh" 
  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.box = "centos/7"
    centralRouter.vm.hostname = "centralRouter"
    centralRouter.vm.network :private_network, ip: '192.168.255.2', adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "irnet"
    centralRouter.vm.network :private_network, #ip: '192.168.255.5', adapter:  3, netmask: "255.255.255.252", 
    virtualbox__intnet: "crnet"
    #centralRouter.vm.network :private_network, ip: '192.168.255.9', adapter:  4, netmask: "255.255.255.252", virtualbox__intnet: "crnet"
    centralRouter.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
  config.vm.define "office1Router" do |office1Router|
    office1Router.vm.box = "centos/7"
    office1Router.vm.hostname = "office1Router"
    office1Router.vm.network :private_network, ip: '192.168.255.6', adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "crnet"
    office1Router.vm.network :private_network, virtualbox__intnet: "localnet"
    office1Router.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
  config.vm.define "office2Router" do |office2Router|
    office2Router.vm.box = "centos/7"
    office2Router.vm.hostname = "office2Router"
    office2Router.vm.network :private_network, ip: '192.168.255.10', adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "crnet"
    office2Router.vm.network :private_network, virtualbox__intnet: "localnet"
    office2Router.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
  ###-----------hosts-------------------------------------------------------------------
  config.vm.define "centralServer" do |centralServer|
    centralServer.vm.box = "centos/7"
    centralServer.vm.hostname = "centralServer"
    centralServer.vm.network :private_network, ip: '192.168.0.50', adapter:  2, netmask: "255.255.255.240", virtualbox__intnet: "localnet"
    centralServer.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
  config.vm.define "office1Server" do |office1Server|
    office1Server.vm.box = "centos/7"
    office1Server.vm.hostname = "office1Server"
    office1Server.vm.network :private_network, ip: '192.168.2.66', adapter:  2, netmask: "255.255.255.192", virtualbox__intnet: "localnet"
    office1Server.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
  config.vm.define "office2Server" do |office2Server|
    office2Server.vm.box = "centos/7"
    office2Server.vm.hostname = "office2Server"
    office2Server.vm.network :private_network, ip: '192.168.1.130', adapter:  2, netmask: "255.255.255.192", virtualbox__intnet: "localnet"
    office2Server.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
end