# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "mailserver" do |mailserver|
  mailserver.vm.hostname = "mailserver"
  mailserver.vm.network "private_network", ip: "192.168.10.10"
  end

  
 end