Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "bacula_server" do |bacula_server|
    bacula_server.vm.box = "centos/7" # need to be commented when Debian like distro used
    #nginx.vm.box = "ubuntu/xenial64" # need to be uncoment when Debian like distro used
    bacula_server.vm.hostname = "bacula-server"
    bacula_server.vm.network :private_network, ip: "10.10.10.10"
    bacula_server.vm.provision "shell", path: "./files/sshd_cfg.sh" 
  end

  config.vm.define "bacula_client" do |bacula_client|
    bacula_client.vm.box = "centos/7" # need to be commented when Debian like distro used
    #nginx.vm.box = "ubuntu/xenial64" # need to be uncoment when Debian like distro used
    bacula_client.vm.hostname = "bacula-client"
    bacula_client.vm.network :private_network, ip: "10.10.10.20"
    bacula_client.vm.provision "shell", path: "./files/sshd_cfg.sh"
  end
end
