Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.box = "centos/7"
    inetRouter.vm.hostname = "inetRouter"
    inetRouter.vm.network :private_network, ip: '192.168.255.10', adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "irnet"
  end

  config.vm.define "inetRouter2" do |inetRouter2|
    inetRouter2.vm.box = "centos/7"
    inetRouter2.vm.hostname = "inetRouter2"
    inetRouter2.vm.network :private_network, ip: '192.168.0.18', adapter:  2, netmask: "255.255.255.240", virtualbox__intnet: "localnet"
  end


  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.box = "centos/7"
    centralRouter.vm.hostname = "centralRouter"
    centralRouter.vm.network :private_network, ip: "192.168.255.9", netmask: "255.255.255.252", adapter:  2,  virtualbox__intnet: "irnet"
  end

  config.vm.define "centalServer" do |centalServer|
    centalServer.vm.box = "centos/7"
    centalServer.vm.hostname = "centralRouter"
    centalServer.vm.network :private_network, ip: "192.168.254.9", netmask: "255.255.255.252", adapter:  2,  virtualbox__intnet: "irnet"
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbooks/ipfiltering.yml"
     ansible.extra_vars = { 
       "def_nginx_port" => "80",
       "nginx_user" => "nginx"
      }
     ansible.verbose = true
  end
  config.vm.provision "shell" do |shell|
    shell.path = "./files/sshd_cfg.sh"
  end 

end