# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end
  config.vm.box = "centos/7"
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.10.10"
  end
  config.vm.define "replica" do |replica|
    replica.vm.hostname = "replica"
    replica.vm.network "private_network", ip: "192.168.10.20"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.groups = {
      "servers" => ["server"],
      "clients" => ["replica"],
      "servers:vars" => {"replica_host" => '192.168.10.20/32',
        "replica_auth_type" => "trust",
        "barman_host" => "192.168.10.20/32",
        "barman_auth_type" => "trust"},
      "clients:vars" => {"replica_host" => '192.168.10.20/32',
        "replica_auth_type" => "trust",
        "barman_host" => "192.168.10.20/32",
        "barman_auth_type" => "trust"

      }
    }
    ansible.playbook = "playbooks/postgresql.yml"
  end
 end