Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
      v.memory = 512
    end
  
    config.vm.define "pam_host" do |pam_host|
      pam_host.vm.box = "centos/7" # need to be commented when Debian like distro used
      #nginx.vm.box = "ubuntu/xenial64" # need to be uncoment when Debian like distro used
      pam_host.vm.hostname = "pam-auth-server"
      pam_host.vm.network :private_network, ip: "10.10.10.20"
      pam_host.vm.provision  "file", source: "./src/pam_check.sh", destination: "/tmp/pam_check.sh"
      pam_host.vm.provision  "file", source: "./src/holydays_table", destination: "/tmp/holydays_table"
      pam_host.vm.provision "shell", path: "./src/pam_config.sh"  
    end
end
