# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            # Подключаем дополнительные диски
            #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end

          box.vm.provision :ansible do |ansible|
            ansible.playbook = "playbooks/mysql.yml"
            ansible.groups = {
              "all" => ["master", "slave"],
              "all:vars" => {"new_root_mysql_pass" => 'vf#cQ8gHKH',
                "repl_user" => "repl",
                "repl_password" => "!OtusLinux2018"
              },
            }
            ansible.host_vars = {
              "master" => {
                "mysql_server_id" => "1",
                "replica_ignore" => ""
                },
              "slave" => {
                "mysql_server_id" => "2",
                "replica_ignore" =>"replicate-ignore-table=bet.events_on_demand\r\nreplicate-ignore-table=bet.v_same_event"
                }
            }
          end

      end
  end
end
